USE AdventureWorks2014
GO

ALTER DATABASE AdventureWorks2014 SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

SET TRANSACTION ISOLATION LEVEL READ COMMITTED
GO

SET NOCOUNT ON

WHILE 1=1 BEGIN

    DECLARE @ModifiedDate DATETIME
    SELECT TOP(1) @ModifiedDate = ModifiedDate
    FROM Person.Person
    WHERE LastName = 'Ivanov'

END