USE KillDB
GO

DBCC SHRINKFILE (N'KillDB_log' , EMPTYFILE)
DBCC SHRINKFILE (N'KillDB_log' , 10)

/*
    --ALTER DATABASE KillDB SET RECOVERY FULL
    BACKUP LOG KillDB TO DISK = 'KillDB.trn' WITH INIT, COMPRESSION

    --ALTER DATABASE KillDB SET RECOVERY SIMPLE
    CHECKPOINT
*/